<?php

/**
 * Ao tentar validar um arquivo XML, se algum erro
 * for encontrado a libxml irá gerar Warnings, o que
 * não creio que seja o mais interessante para nós.
 * Para evitar que isso aconteça, você pode determinar
 * que irá obter os erros por sua própria conta. Lembre-se
 * que esta função abaixo deve ser chamada antes de
 * instanciar qualquer objeto da classe DomDocument!
 */
#$output = shell_exec('PDFtoPrinter.exe filename.pdf "\\ESTACAO1-SN\ELGIN i9"');

#$x = '"C:\Program Files (x86)\Foxit Software\Foxit PDF Reader\FoxitPDFReader.exe" /t "C:\laragon\www\filename.pdf"';
#c:\Program Files\Secure Soft\XML Signer>"XML Signer.exe" c:\TestFile.xml c:\TestFile[signed.xml]


//$x = '"C:\Program Files (x86)\Secure Soft\XML Signer "'
$dir_origem =explode(':',$_SERVER['DOCUMENT_ROOT']);

$z = '"'.$dir_origem[0].'://Program Files (x86)/Secure Soft/XML Signer/XML Signer.exe" "'.$dir_origem[0].'://XML_SIGN/ENTRADA/cep.xml" "'.$dir_origem[0].'://XML_SIGN/SAIDA/cep_assinado.xml"';
$output = shell_exec( $z);

echo "<pre>$output</pre>";
echo "<pre>$z</pre>";

// $info_assinado = file_get_contents('C:\XML_SIGN\SAIDA\cep_assinado.xml');
// $info_assinado_base64  = base64_encode($info_assinado);


// $curl = curl_init();

// curl_setopt_array($curl, array(
//   CURLOPT_URL => 'https://wsh.registrocivil.org.br/inscricaoCPF.cfc',
//   CURLOPT_RETURNTRANSFER => true,
//   CURLOPT_ENCODING => '',
//   CURLOPT_MAXREDIRS => 10,
//   CURLOPT_TIMEOUT => 0,
//   CURLOPT_SSL_VERIFYHOST => 0,
//   CURLOPT_SSL_VERIFYPEER => 0,
//   CURLOPT_FOLLOWLOCATION => true,
//   CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
//   CURLOPT_CUSTOMREQUEST => 'POST',
//   CURLOPT_POSTFIELDS =>'<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
//     <Body>
//         <inscricaoCPF xmlns="http://DefaultNamespace">
//             <inscricaoCPF>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iSVNPLTg4NTktMSI/Pg0KPGNwZl9nZXJhcj4NCjxoYXNoX2Zvcm5lY2Vkb3I+OTBBQ0RBMTJEOEZGMzlDRUEzQTRGMkNDQzBCNDI4ODE5QjlBMkU2RDlCRTY0QURBRjBFRkE4Q0ZFN0FBODQwODwvaGFzaF9mb3JuZWNlZG9yPg0KPGRudj4xMjMzNDU2Nzg5MTA8L2Rudj4NCjxmbGFnX2Rudl9pZ25vcmFkYT5TPC9mbGFnX2Rudl9pZ25vcmFkYT4NCjxkYXRhX25hc2NpbWVudG8+MTAvMTAvMjAyMDwvZGF0YV9uYXNjaW1lbnRvPg0KPGRhdGFfcmVnaXN0cm8+MTAvMTAvMjAyMDwvZGF0YV9yZWdpc3Rybz4NCjxzZXhvPk08L3NleG8+DQo8Y29kX2liZ2VfY2lkYWRlX25hdHVyYWxpZGFkZT4yMTA4NjAzPC9jb2RfaWJnZV9jaWRhZGVfbmF0dXJhbGlkYWRlPg0KPGNlcD42NTIwMDAwMDwvY2VwPg0KPGVuZGVyZWNvPmVuZGVyZWNvIGRvbWljaWxpbzwvZW5kZXJlY28+DQo8bnVtX2VuZD45OTwvbnVtX2VuZD4NCjxjb21wbGVtZW50bz5jb21wbGVtZW50bzwvY29tcGxlbWVudG8+DQo8YmFpcnJvPmJhaXJybzwvYmFpcnJvPg0KPGNvZF9pYmdlX2NpZGFkZV9kb21pY2lsaW8+MjEwODYwMzwvY29kX2liZ2VfY2lkYWRlX2RvbWljaWxpbz4NCjxudW1fdGVsZWZvbmU+PC9udW1fdGVsZWZvbmU+DQo8bnVtX2NlbHVsYXI+PC9udW1fY2VsdWxhcj4NCjxkZGRfY2VsdWxhcj48L2RkZF9jZWx1bGFyPg0KPGRkZF90ZWxlZm9uZT48L2RkZF90ZWxlZm9uZT4NCjxtYXRyaWN1bGE+MDMwMDcyMDE1NTE5OTkxMDAwNTMyODEwMDQyMjkwNzQ8L21hdHJpY3VsYT4NCjxub21lX2NyaWFuY2E+Tk9NRSBDUklBTkNBIFRFU1RFPC9ub21lX2NyaWFuY2E+DQo8bm9tZV9nZW5pdG9yYT5SSVpSIFpPRVZIIFdWIExPUkVWUklaPC9ub21lX2dlbml0b3JhPg0KPG5vbWVfZ2VuaXRvcj48L25vbWVfZ2VuaXRvcj4NCjxjcGZfZ2VuaXRvcmE+MDMyODUzNDU2MDg8L2NwZl9nZW5pdG9yYT4NCjxjcGZfZ2VuaXRvcj48L2NwZl9nZW5pdG9yPg0KPC9jcGZfZ2VyYXI+MIAGCSqGSIb3DQEHAqCAMIACAQExDzANBglghkgBZQMEAgEFADCABgkqhkiG9w0BBwEAAKCAMIIH2TCCBcGgAwIBAgIQNbq7XCQ/lZsg/j0KyBt9QjANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc1MB4XDTIxMDUxNDEzMTUyOFoXDTI0MDUxMzEzMTUyOFowgecxCzAJBgNVBAYTAkJSMRMwEQYDVQQKDApJQ1AtQnJhc2lsMRMwEQYDVQQLDApQcmVzZW5jaWFsMRcwFQYDVQQLDA4wNjA1Mjc1NzAwMDEwNTE2MDQGA1UECwwtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRUwEwYDVQQLDAxSRkIgZS1DUEYgQTMxFDASBgNVBAsMCyhlbSBicmFuY28pMTAwLgYDVQQDDCdBTlRPTklPIEpPU0UgTUFSVElOUyBHQVJDSUE6MDYxNTEzMjAzMDEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDHLjc/m1rbf3YHVV9O7BM5ag5wJbVo6gB/wMwprkwpjZyI5H53+JVaM+UTANwenPbvKnsAL+gTNPxLkVP+Pz1ayjPSTNVJfi6VoTDt5TOhgP5kORyfkAj204q1dpMqWNUeVG1RsuRKbPKBiMgLNbpSHIZmiPTQ5afVit1TImqZCXa8uDz1u8wZlaZS7Py2jgnQ0/MFxF0rNjbNVyjm1YTgVPra1/0ceyqEdJZ2GtUAfSvse+RuYlvQOP7vvoD+yplkiGZ5FBUlQczTHUMeMaj3ywv3Rq/971Q8tTu7CDk2zOy50UzsCM6WyRd2piKANqNL72myZB+bDGQMl/D0a60hAgMBAAGjggLtMIIC6TCBnAYDVR0RBIGUMIGRoD4GBWBMAQMBoDUEMzEyMDYxOTk1MDYxNTEzMjAzMDEwMDAwMDAwMDAwMDAwMDQxNDc5NTcyMDExMFNFU1BNQaAXBgVgTAEDBqAOBAwwMDAwMDAwMDAwMDCgHgYFYEwBAwWgFQQTMDAwMDAwMDAwMDAwMDAwMDAwMIEWdG9ueXRlY0BvdXRsb29rLmNvbS5icjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFFN9f52+0WHQILran+OJpxNzWM1CMH8GA1UdIAR4MHYwdAYGYEwBAgMGMGowaAYIKwYBBQUHAgEWXGh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL0FDX0NlcnRpc2lnbl9SRkIvRFBDX0FDX0NlcnRpc2lnbl9SRkIucGRmMIG8BgNVHR8EgbQwgbEwV6BVoFOGUWh0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL0FDQ2VydGlzaWduUkZCRzUvTGF0ZXN0Q1JMLmNybDBWoFSgUoZQaHR0cDovL2ljcC1icmFzaWwub3V0cmFsY3IuY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0NlcnRpc2lnblJGQkc1L0xhdGVzdENSTC5jcmwwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBrAYIKwYBBQUHAQEEgZ8wgZwwXwYIKwYBBQUHMAKGU2h0dHA6Ly9pY3AtYnJhc2lsLmNlcnRpc2lnbi5jb20uYnIvcmVwb3NpdG9yaW8vY2VydGlmaWNhZG9zL0FDX0NlcnRpc2lnbl9SRkJfRzUucDdjMDkGCCsGAQUFBzABhi1odHRwOi8vb2NzcC1hYy1jZXJ0aXNpZ24tcmZiLmNlcnRpc2lnbi5jb20uYnIwDQYJKoZIhvcNAQELBQADggIBAFn8BQu7wG3hQ2ZgFKF3Bb9HWVRsjGTlirQ6WXnmc+dP8xHtAfSRCCEEUqUi9c2sL27unaU7Xm5FyqariUoyyWhCaimNWFRAVfmnpTrHceEJAQ+s0+cAOhww3P8XN6JiLmi8U174/kSDHM2Q9vHZFulHg94rE8dEkIkJAmsXHMxCOmN6tW4vZvOEgLvnrPVm9mnxJFGoQlK2UsPAFZixC/MU5XNmR1RIDM5tL2kwsqAUf7UyaRbIajjWyPdN3f0Q3XaKsPhLu18hEMF/0eRx9GN7ve8UmTrKBsiwXCwgugWnwVkYKuJlxsO6hnUalmFo52WNY6T2GsnyAz/dpHYXvu/kr+pALRjjRA+WkE5dT0l3puzTmfI3BL05vb/1yvNzNOggSSl/NryxdXrmCfqzgMD51osCjfHbXKg5b1qNqub3bdSzy3UhkPOOk79HwzjHpPF2bcUj2yOHJye3mFd8MivuspsKNrCM5NwHL/GXVt0oioaXFWGnO2c6euI5bTnRfVQDaWic7IGVC58lYas9o8EPEwPEsgPg2ouBWwYXUiq0hltVSFmIpGCcfPSajMpRsxBfBBTjJexCA8JKxvgbqAiIAE/zxYULTkikt5vok+pMoIGB/2yGWAy8C7r5Gad4T6tQwVEJqcP0HtZZP0EefpW3Voeda3+HwwphngKVCR4qAAAxggO8MIIDuAIBATCBjDB4MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc1AhA1urtcJD+VmyD+PQrIG31CMA0GCWCGSAFlAwQCAQUAoIICADAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMjA4MTkxNzA4NDNaMC0GCSqGSIb3DQEJNDEgMB4wDQYJYIZIAWUDBAIBBQChDQYJKoZIhvcNAQELBQAwLwYJKoZIhvcNAQkEMSIEIHaQDAnFmnMMbpFvK5zKxMaMZ8vy8FyG0mm7In2fMRPbMIGUBgsqhkiG9w0BCRACDzGBhDCBgQYIYEwBBwEBAgMwLzALBglghkgBZQMEAgEEILFuiLv3cyKmeZW3kHh3jtPQ6nyIWHtvbVGLcV6PdqPVMEQwQgYLKoZIhvcNAQkQBQEWM2h0dHA6Ly9wb2xpdGljYXMuaWNwYnJhc2lsLmdvdi5ici9QQV9BRF9SQl92Ml8zLmRlcjCBzgYLKoZIhvcNAQkQAi8xgb4wgbswgbgwgbUEIDV7/WB7sjes985cdUIuvawKIMtxubvWsVQhcmhKDanFMIGQMHykejB4MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc1AhA1urtcJD+VmyD+PQrIG31CMA0GCSqGSIb3DQEBCwUABIIBAK9WQYmG816ExXFXGlv3Rkhwl4VDVSeHA6YTBNgy3XWhTyTQqCaWwoyJrT0yrtT3ITD7nFruiG81fymVOi3g1Gs8qz4EyZXexq858++fOA777YQ66dEVsn2Z8RdqzFkde1NeeWizwYHLGaDe2GcJDAvjF7UegwRj8VyBla8dIP30p4u/cjLg7sB1SF+4On9Y6ZqYwXWUZzknSm39Y48hOsj8w50YYGMa6HqJGnZIEvPN2TlYL2m/HRGnsmXccNjWVft8NhEniF+owTqY0PkPIblYpzIYeGKg1RBxjz3cVLZ+0pvi2yh3zsc8RpMwGMvKB4+n+EMJCoSUUKQRG4RTz1AAAAAAAAA=</inscricaoCPF>
//         </inscricaoCPF>
//     </Body>
// </Envelope>',
//   CURLOPT_HTTPHEADER => array(
//     'Content-Type: text/xml; charset=utf-8',
//     'SoapAction: '
//   ),
// ));

// $response = curl_exec($curl);

// curl_close($curl);
// echo $response;
// $arq = simplexml_load_string($response);
// var_dump($arq);

?>